//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cross.Modules.ChildPageList {
    
    
    public partial class Settings {
        
        /// <summary>
        /// plParentTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plParentTab;
        
        /// <summary>
        /// ddlParentTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlParentTab;
        
        /// <summary>
        /// plIncludeSelf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plIncludeSelf;
        
        /// <summary>
        /// chkIncludeSelf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkIncludeSelf;
        
        /// <summary>
        /// plIncludeInvisible control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plIncludeInvisible;
        
        /// <summary>
        /// chkIncludeInvisible control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkIncludeInvisible;
        
        /// <summary>
        /// plRecursive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plRecursive;
        
        /// <summary>
        /// chkRecursive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkRecursive;
        
        /// <summary>
        /// plDisplayIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plDisplayIcon;
        
        /// <summary>
        /// chkDisplayIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkDisplayIcon;
        
        /// <summary>
        /// plListTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plListTemplate;
        
        /// <summary>
        /// ddlListTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlListTemplate;
        
        /// <summary>
        /// plColumnCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plColumnCount;
        
        /// <summary>
        /// txtColumnCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtColumnCount;
        
        /// <summary>
        /// Regularexpressionvalidator4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator Regularexpressionvalidator4;
        
        /// <summary>
        /// plLinkTarget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::DotNetNuke.UI.UserControls.LabelControl plLinkTarget;
        
        /// <summary>
        /// ddlLinkTarget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlLinkTarget;
        
        /// <summary>
        /// cmdUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmdUpdate;
        
        /// <summary>
        /// cmdReturn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmdReturn;
    }
}
